  //bu projeden bağımsız olarak çalıştığım bazı paketler
  
  lottie: ^1.4.1
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  firebase_database: ^6.0.0
  firebase_messaging: ^12.0.2
  firebase_remote_config: ^2.0.14
  permission_handler: ^10.0.0
  connectivity: ^3.0.6
  flutter_inappwebview: ^5.4.3+7 
  awesome_notifications: 0.6.21
  url_launcher: ^6.1.5
  carousel_slider: ^2.2.1
  cached_network_image: ^3.2.1
  persistent_bottom_nav_bar: ^2.1.0
  flutter_staggered_grid_view: ^0.3.2
  external_app_launcher: ^3.1.0
  icofont_flutter: ^1.3.0
